#############
# Frontend  #
#############

[[frontend]]
name = "yew"
crates-io = "Yew"
homepage = "https://yew.rs"
repo = "https://github.com/yewstack/yew"
vdom = true
ssr = false
rendering = "html"
architecture = "react"

[[frontend]]
name = "Seed"
crates-io = "seed"
homepage = "http://seed-rs.org/"
repo = "https://github.com/seed-rs/seed"
vdom = true
ssr = false
rendering = "html"
architecture = "tea"
outdated = true

[[frontend]]
name = "sauron"
repo = "https://github.com/ivanceras/sauron"
crates-io = "sauron"
vdom = true
ssr = true
rendering = "html"
architecture = "tea"

[[frontend]]
name = "mogwai"
repo = "https://github.com/schell/mogwai"
crates-io = "mogwai"
vdom = false
ssr = true
rendering = "html"
outdated = true

[[frontend]]
name = "dominator"
repo = "https://github.com/Pauan/rust-dominator"
crates-io = "dominator"
vdom = false
ssr = false
rendering = "html"
architecture = "frp"

[[frontend]]
name = "Sycamore"
homepage = "https://sycamore-rs.netlify.app"
repo = "https://github.com/sycamore-rs/sycamore"
crates-io = "sycamore"
vdom = false
ssr = true
rendering = "html"
architecture = "frp"

[[frontend]]
name = "Dioxus"
homepage = "https://dioxuslabs.com/"
repo = "https://github.com/dioxuslabs/dioxus"
crates-io = "dioxus"
vdom = true
ssr = true
rendering = "html"

[[frontend]]
name = "MoonZoon"
homepage = "http://moonzoon.rs/"
repo = "https://github.com/MoonZoon/MoonZoon"
vdom = false
ssr = false
rendering = "html"
architecture = "frp"

[[frontend]]
name = "Silkenweb"
crates-io = "silkenweb"
repo = "https://github.com/silkenweb/silkenweb"
vdom = false
ssr = true
rendering = "html"
outdated = false
architecture = "frp"

[[frontend]]
homepage = "https://chinedufn.github.io/percy/"
name = "percy"
repo = "https://github.com/chinedufn/percy"
ssr = true
vdom = true
outdated = true
rendering = "html"

[[frontend]]
name = "spair"
crates-io = "spair"
repo = "https://github.com/aclueless/spair"
ssr = false
vdom = false
rendering = "html"
outdated = true

[[frontend]]
homepage = "https://www.egui.rs/"
name = "egui"
crates-io = "egui"
repo = "https://github.com/emilk/egui"
ssr = false
vdom = false
rendering = "canvas"
architecture = "imgui"

[[frontend]]
homepage = "https://iced.rs/"
name = "Iced"
crates-io = "iced"
repo = "https://github.com/iced-rs/iced"
ssr = false
vdom = false
rendering = "canvas"
architecture = "tea"

[[frontend]]
name = "frender"
crates-io = "frender"
homepage = "https://frender-rs.github.io/frender/"
repo = "https://github.com/frender-rs/frender"
vdom = true
ssr = false
outdated = true

[[frontend]]
outdated = true
crates-io = "dodrio"
name = "dodrio"
repo = "https://github.com/fitzgen/dodrio"

[[frontend]]
outdated = true
name = "draco"
repo = "https://github.com/utkarshkukreti/draco"

[[frontend]]
outdated = true
name = "dumle"
repo = "https://github.com/axelf4/dumle"

[[frontend]]
outdated = true
name = "mika"
repo = "https://gitlab.com/limira-rs/mika"
crates-io = "mika"

[[frontend]]
outdated = true
name = "ruukh"
repo = "https://github.com/csharad/ruukh"

[[frontend]]
outdated = true
name = "smithy"
crates-io = "smithy"
repo = "https://github.com/rbalicki2/smithy"
homepage = "https://www.smithy.rs/"

[[frontend]]
outdated = true
name = "squark"
repo = "https://github.com/rail44/squark"

[[frontend]]
outdated = true
name = "stdweb"
crates-io = "stdweb"
repo = "https://github.com/koute/stdweb"

[[frontend]]
outdated = true
name = "willow"
repo = "https://github.com/sindreij/willow"

[[frontend]]
name = "Leptos"
repo = "https://github.com/gbj/leptos"
crates-io = "leptos"
vdom = false
architecture = "frp"
ssr = true
rendering = "html"

############
#  Server  #
############

[[server]]
name = "actix-web"
homepage = "https://actix.rs/"
repo = "https://github.com/actix/actix-web"
crates-io = "actix-web"
https = true
http2 = true
base = "tokio"
async = true
client = false

[[server]]
name = "axum"
repo = "https://github.com/tokio-rs/axum"
crates-io = "axum"
https = true
http2 = true
base = "hyper"
async = true
client = false

[[server]]
name = "gotham"
homepage = "http://gotham.rs"
repo = "https://github.com/gotham-rs/gotham"
crates-io = "gotham"
https = true
http2 = false
base = "hyper"
async = true
client = false

[[server]]
name = "rocket"
homepage = "https://rocket.rs"
repo = "https://github.com/SergioBenitez/rocket"
crates-io = "rocket"
https = true
http2 = true
base = "hyper"
async = true
client = false

[[server]]
name = "Thruster"
repo = "https://github.com/trezm/Thruster"
crates-io = "thruster"
https = true
http2 = true
base = "tokio (or hyper)"
async = true
client = false

[[server]]
name = "Tide"
repo = "https://github.com/rustasync/tide"
crates-io = "tide"
https = true
http2 = false
base = "async-std"
async = true
client = false

[[server]]
name = "warp"
repo = "https://github.com/seanmonstar/warp"
crates-io = "warp"
https = true
http2 = true
base = "hyper"
async = true
client = false

[[server]]
name = "salvo"
repo = "https://github.com/salvo-rs/salvo"
crates-io = "salvo"
https = true
http2 = true
base = "hyper"
async = true
client = false

[[server]]
name = "trillium"
repo = "https://github.com/trillium-rs/trillium"
crates-io = "trillium"
homepage = "https://trillium.rs"
https = true
http2 = false
base = "tokio"
async = true
client = false

[[server]]
name = "Poem"
repo = "https://github.com/poem-web/poem"
crates-io = "poem"
https = true
http2 = true
base = "hyper"
async = true
client = false

[[server]]
name = "Viz"
repo = "https://github.com/viz-rs/viz"
homepage = "https://viz.rs"
crates-io = "viz"
https = true
http2 = true
base = "hyper"
async = true
client = false

[[server]]
name = "hyper"
homepage = "http://hyper.rs/"
repo = "https://github.com/hyperium/hyper"
crates-io = "hyper"
low-level = true
outdated = false
async = true
http2 = true
https = true
client = true

[[server]]
name = "tiny-http"
repo = "https://github.com/tiny-http/tiny-http"
crates-io = "tiny_http"
low-level = true
outdated = false
async = false
http2 = false
https = true
client = false

[[server]]
name = "actix-http"
homepage = "https://github.com/actix/actix-web/tree/master/actix-http"
repo = "https://github.com/actix/actix-web"
crates-io = "actix-http"
low-level = true
outdated = false
async = true
http2 = true
https = true
client = true

[[server]]
name = "civet"
repo = "https://github.com/wycats/rust-civet"
outdated = true
crates-io = "civet"

[[server]]
name = "conduit"
repo = "https://github.com/conduit-rust/conduit"
outdated = true
crates-io = "conduit"

[[server]]
name = "cargonaouts"
repo = "https://github.com/cargonauts-rs/cargonauts"
outdated = true
crates-io = "cargonaouts"

[[server]]
name = "hydrogen"
repo = "https://github.com/nathansizemore/hydrogen"
outdated = true
crates-io = "hydrogen"

[[server]]
name = "iron"
repo = "https://github.com/iron/iron"
outdated = true
crates-io = "iron"

[[server]]
name = "kinglet"
repo = "https://github.com/pyfisch/kinglet"
outdated = true
crates-io = "kinglet"

[[server]]
name = "nickel"
repo = "https://github.com/nickel-org/nickel.rs/"
outdated = true
crates-io = "nickel"

[[server]]
name = "rouille"
repo = "https://github.com/tomaka/rouille"
outdated = true
crates-io = "rouille"

[[server]]
name = "rustless"
repo = "https://github.com/rustless/rustless"
outdated = true
crates-io = "rustless"

[[server]]
name = "rustful"
repo = "https://github.com/Ogeon/rustful"
outdated = true
crates-io = "rustful"

[[server]]
name = "shio"
repo = "https://github.com/mehcode/shio-rs"
outdated = true
crates-io = "shio"

[[server]]
name = "sappers"
repo = "https://github.com/sappworks/sapper"
outdated = true
crates-io = "sappers"

[[server]]
name = "solicit"
repo = "https://github.com/mlalic/solicit"
outdated = true
crates-io = "solicit"

[[server]]
name = "tower-web"
repo = "https://github.com/carllerche/tower-web"
outdated = true
crates-io = "tower-web"

[[server]]
name = "tk-http"
repo = "https://github.com/swindon-rs/tk-http"
outdated = true
crates-io = "tk-http"

#############
# Template  #
#############

[[template]]
name = "sailfish"
homepage = "https://sailfish.netlify.app"
repo = "https://github.com/Kogia-sima/sailfish/"
crates-io = "sailfish"

[[template]]
name = "tera"
homepage = "https://tera.netlify.com/"
repo = "https://github.com/Keats/tera"
crates-io = "tera"

[[template]]
name = "mustache"
repo = "https://github.com/nickel-org/rust-mustache"
crates-io = "mustache"

[[template]]
name = "liquid"
repo = "https://github.com/cobalt-org/liquid-rust"

[[template]]
name = "handlebars"
repo = "https://github.com/sunng87/handlebars-rust"
crates-io = "handlebars"

[[template]]
name = "horrorshow"
repo = "https://github.com/Stebalien/horrorshow-rs"
crates-io = "horrorshow"

[[template]]
name = "maud"
repo = "https://github.com/lfairy/maud"
homepage = "https://lfairy.gitbooks.io/maud/content"
crates-io = "maud"

[[template]]
name = "askama"
repo = "https://github.com/djc/askama"
crates-io = "askama"

[[template]]
name = "stpl"
repo = "https://github.com/dpc/stpl"

[[template]]
name = "ructe"
repo = "https://github.com/kaj/ructe"
crates-io = "ructe"

[[template]]
name = "typed-html"
repo = "https://github.com/bodil/typed-html"
crates-io = "typed-html"

#############
# Websocket #
#############

[[websocket]]
name = "tungstenite"
crates-io = "tungstenite"
repo = "https://github.com/snapview/tungstenite-rs"
server = true
client = true
async = true

[[websocket]]
name = "tokio-tungstenite"
crates-io = "tokio-tungstenite"
repo = "https://github.com/snapview/tokio-tungstenite"
server = true
client = true
async = true

[[websocket]]
name = "actix-web"
crates-io = "actix-web-actors"
repo = "https://github.com/actix/actix-web"
homepage = "https://actix.rs/docs/websockets/"
server = true
client = true
async = true

[[websocket]]
name = "ws-rs"
repo = "https://github.com/housleyjk/ws-rs"
crates-io = "ws"
server = true
client = true
async = true

[[websocket]]
name = "websocket"
repo = "https://github.com/websockets-rs/rust-websocket"
homepage = "https://websockets-rs.github.io/rust-websocket/"
crates-io = "websocket"
server = true
client = true
async = true
outdated = true
